// Code generated by cmd/gen-numbers. DO NOT EDIT.

//go:build (!winescape_freebsd && windows && arm64) || (linux && arm64)

package winescape

const (
	sysRead            uintptr = 63
	sysWrite           uintptr = 64
	sysOpen            uintptr = 0
	sysClose           uintptr = 57
	sysFstat           uintptr = 80
	sysLseek           uintptr = 62
	sysPread64         uintptr = 67
	sysPwrite64        uintptr = 68
	sysAccess          uintptr = 0
	sysGetpid          uintptr = 172
	sysMkdir           uintptr = 0
	sysRmdir           uintptr = 0
	sysRename          uintptr = 0
	sysUnlink          uintptr = 0
	sysSymlink         uintptr = 0
	sysReadlink        uintptr = 0
	sysGetdents64      uintptr = 61
	sysGetdirentries   uintptr = 0
	sysOpenat          uintptr = 56
	sysMkdirat         uintptr = 34
	sysNewfstatat      uintptr = 79
	sysFstatat         uintptr = 0
	sysUnlinkat        uintptr = 35
	sysRenameat        uintptr = 38
	sysRenameat2       uintptr = 276
	sysReadlinkat      uintptr = 78
	sysFaccessat       uintptr = 48
	sysPipe2           uintptr = 59
	sysDup3            uintptr = 24
	sysMmap            uintptr = 222
	sysMunmap          uintptr = 215
	sysInotifyInit1    uintptr = 26
	sysInotifyAddWatch uintptr = 27
	sysInotifyRmWatch  uintptr = 28
	sysGetuid          uintptr = 174
	sysGetgid          uintptr = 176
	sysGeteuid         uintptr = 175
	sysGetegid         uintptr = 177
	sysGetppid         uintptr = 173
	sysSocket          uintptr = 198
	sysConnect         uintptr = 203
	sysBind            uintptr = 200
	sysListen          uintptr = 201
	sysAccept4         uintptr = 242
	sysIoctl           uintptr = 29
	sysNanosleep       uintptr = 101
	sysClockGettime    uintptr = 113
	sysClockNanosleep  uintptr = 115
	sysKill            uintptr = 129
	sysWait4           uintptr = 260
	sysFchmodat        uintptr = 53
	sysFchownat        uintptr = 54
	sysUtimensat       uintptr = 88
	sysFtruncate       uintptr = 46
	sysSymlinkat       uintptr = 36
	sysCopyFileRange   uintptr = 285
	sysFlock           uintptr = 32
	sysStatfs          uintptr = 43
	sysFstatfs         uintptr = 44
	sysExecve          uintptr = 221
	sysClone           uintptr = 220
	sysSetsid          uintptr = 157
	sysChdir           uintptr = 49
	sysExitGroup       uintptr = 94
	sysRtSigprocmask   uintptr = 135
	sysRtSigaction     uintptr = 134
	sysPpoll           uintptr = 73
	sysCloseRange      uintptr = 436
	sysFcntl           uintptr = 25
)
