// Code generated by cmd/gen-numbers. DO NOT EDIT.

//go:build (!windows && !linux && !freebsd) || (!amd64 && !arm64)

package winescape

const (
	sysRead            uintptr = 0
	sysWrite           uintptr = 0
	sysOpen            uintptr = 0
	sysClose           uintptr = 0
	sysFstat           uintptr = 0
	sysLseek           uintptr = 0
	sysPread64         uintptr = 0
	sysPwrite64        uintptr = 0
	sysAccess          uintptr = 0
	sysGetpid          uintptr = 0
	sysMkdir           uintptr = 0
	sysRmdir           uintptr = 0
	sysRename          uintptr = 0
	sysUnlink          uintptr = 0
	sysSymlink         uintptr = 0
	sysReadlink        uintptr = 0
	sysGetdents64      uintptr = 0
	sysGetdirentries   uintptr = 0
	sysOpenat          uintptr = 0
	sysMkdirat         uintptr = 0
	sysNewfstatat      uintptr = 0
	sysFstatat         uintptr = 0
	sysUnlinkat        uintptr = 0
	sysRenameat        uintptr = 0
	sysRenameat2       uintptr = 0
	sysReadlinkat      uintptr = 0
	sysFaccessat       uintptr = 0
	sysPipe2           uintptr = 0
	sysDup3            uintptr = 0
	sysMmap            uintptr = 0
	sysMunmap          uintptr = 0
	sysInotifyInit1    uintptr = 0
	sysInotifyAddWatch uintptr = 0
	sysInotifyRmWatch  uintptr = 0
	sysGetuid          uintptr = 0
	sysGetgid          uintptr = 0
	sysGeteuid         uintptr = 0
	sysGetegid         uintptr = 0
	sysGetppid         uintptr = 0
	sysSocket          uintptr = 0
	sysConnect         uintptr = 0
	sysBind            uintptr = 0
	sysListen          uintptr = 0
	sysAccept4         uintptr = 0
	sysIoctl           uintptr = 0
	sysNanosleep       uintptr = 0
	sysClockGettime    uintptr = 0
	sysClockNanosleep  uintptr = 0
	sysKill            uintptr = 0
	sysWait4           uintptr = 0
	sysFchmodat        uintptr = 0
	sysFchownat        uintptr = 0
	sysUtimensat       uintptr = 0
	sysFtruncate       uintptr = 0
	sysSymlinkat       uintptr = 0
	sysCopyFileRange   uintptr = 0
	sysFlock           uintptr = 0
	sysStatfs          uintptr = 0
	sysFstatfs         uintptr = 0
	sysExecve          uintptr = 0
	sysClone           uintptr = 0
	sysSetsid          uintptr = 0
	sysChdir           uintptr = 0
	sysExitGroup       uintptr = 0
	sysRtSigprocmask   uintptr = 0
	sysRtSigaction     uintptr = 0
	sysPpoll           uintptr = 0
	sysCloseRange      uintptr = 0
	sysFcntl           uintptr = 0
)
