// Code generated by cmd/gen-numbers. DO NOT EDIT.

//go:build (winescape_freebsd && windows && arm64) || (freebsd && arm64)

package winescape

const (
	sysRead            uintptr = 3
	sysWrite           uintptr = 4
	sysOpen            uintptr = 5
	sysClose           uintptr = 6
	sysFstat           uintptr = 551
	sysLseek           uintptr = 478
	sysPread64         uintptr = 475
	sysPwrite64        uintptr = 476
	sysAccess          uintptr = 33
	sysGetpid          uintptr = 20
	sysMkdir           uintptr = 136
	sysRmdir           uintptr = 137
	sysRename          uintptr = 128
	sysUnlink          uintptr = 10
	sysSymlink         uintptr = 57
	sysReadlink        uintptr = 58
	sysGetdents64      uintptr = 0
	sysGetdirentries   uintptr = 554
	sysOpenat          uintptr = 499
	sysMkdirat         uintptr = 500
	sysNewfstatat      uintptr = 0
	sysFstatat         uintptr = 552
	sysUnlinkat        uintptr = 503
	sysRenameat        uintptr = 501
	sysRenameat2       uintptr = 0
	sysReadlinkat      uintptr = 505
	sysFaccessat       uintptr = 489
	sysPipe2           uintptr = 538
	sysDup3            uintptr = 545
	sysMmap            uintptr = 477
	sysMunmap          uintptr = 73
	sysInotifyInit1    uintptr = 0
	sysInotifyAddWatch uintptr = 0
	sysInotifyRmWatch  uintptr = 0
	sysGetuid          uintptr = 24
	sysGetgid          uintptr = 47
	sysGeteuid         uintptr = 25
	sysGetegid         uintptr = 43
	sysGetppid         uintptr = 39
	sysSocket          uintptr = 97
	sysConnect         uintptr = 98
	sysBind            uintptr = 104
	sysListen          uintptr = 106
	sysAccept4         uintptr = 541
	sysIoctl           uintptr = 54
	sysNanosleep       uintptr = 240
	sysClockGettime    uintptr = 232
	sysClockNanosleep  uintptr = 244
	sysKill            uintptr = 37
	sysWait4           uintptr = 7
	sysFchmodat        uintptr = 490
	sysFchownat        uintptr = 491
	sysUtimensat       uintptr = 547
	sysFtruncate       uintptr = 480
	sysSymlinkat       uintptr = 504
	sysCopyFileRange   uintptr = 569
	sysFlock           uintptr = 131
	sysStatfs          uintptr = 396
	sysFstatfs         uintptr = 397
	sysExecve          uintptr = 59
	sysClone           uintptr = 0
	sysSetsid          uintptr = 0
	sysChdir           uintptr = 0
	sysExitGroup       uintptr = 0
	sysRtSigprocmask   uintptr = 0
	sysRtSigaction     uintptr = 0
	sysPpoll           uintptr = 0
	sysCloseRange      uintptr = 0
	sysFcntl           uintptr = 0
)
