// Code generated by cmd/gen-numbers. DO NOT EDIT.

//go:build (!winescape_freebsd && windows && amd64) || (linux && amd64)

package winescape

const (
	sysRead            uintptr = 0
	sysWrite           uintptr = 1
	sysOpen            uintptr = 2
	sysClose           uintptr = 3
	sysFstat           uintptr = 5
	sysLseek           uintptr = 8
	sysPread64         uintptr = 17
	sysPwrite64        uintptr = 18
	sysAccess          uintptr = 21
	sysGetpid          uintptr = 39
	sysMkdir           uintptr = 83
	sysRmdir           uintptr = 84
	sysRename          uintptr = 82
	sysUnlink          uintptr = 87
	sysSymlink         uintptr = 88
	sysReadlink        uintptr = 89
	sysGetdents64      uintptr = 217
	sysGetdirentries   uintptr = 0
	sysOpenat          uintptr = 257
	sysMkdirat         uintptr = 258
	sysNewfstatat      uintptr = 262
	sysFstatat         uintptr = 0
	sysUnlinkat        uintptr = 263
	sysRenameat        uintptr = 264
	sysRenameat2       uintptr = 316
	sysReadlinkat      uintptr = 267
	sysFaccessat       uintptr = 269
	sysPipe2           uintptr = 293
	sysDup3            uintptr = 292
	sysMmap            uintptr = 9
	sysMunmap          uintptr = 11
	sysInotifyInit1    uintptr = 294
	sysInotifyAddWatch uintptr = 254
	sysInotifyRmWatch  uintptr = 255
	sysGetuid          uintptr = 102
	sysGetgid          uintptr = 104
	sysGeteuid         uintptr = 107
	sysGetegid         uintptr = 108
	sysGetppid         uintptr = 110
	sysSocket          uintptr = 41
	sysConnect         uintptr = 42
	sysBind            uintptr = 49
	sysListen          uintptr = 50
	sysAccept4         uintptr = 288
	sysIoctl           uintptr = 16
	sysNanosleep       uintptr = 35
	sysClockGettime    uintptr = 228
	sysClockNanosleep  uintptr = 230
	sysKill            uintptr = 62
	sysWait4           uintptr = 61
	sysFchmodat        uintptr = 268
	sysFchownat        uintptr = 260
	sysUtimensat       uintptr = 280
	sysFtruncate       uintptr = 77
	sysSymlinkat       uintptr = 266
	sysCopyFileRange   uintptr = 326
	sysFlock           uintptr = 73
	sysStatfs          uintptr = 137
	sysFstatfs         uintptr = 138
	sysExecve          uintptr = 59
	sysClone           uintptr = 56
	sysSetsid          uintptr = 112
	sysChdir           uintptr = 80
	sysExitGroup       uintptr = 231
	sysRtSigprocmask   uintptr = 14
	sysRtSigaction     uintptr = 13
	sysPpoll           uintptr = 271
	sysCloseRange      uintptr = 436
	sysFcntl           uintptr = 72
)
